// category
export const ALL_CATEGORYS = "ALL_CATEGORYS"
export const CATEGORYS_SUCCESS = "CATEGORYS_SUCCESS"
export const CATEGORYS_FAIL = "CATEGORYS_FAIL"

// login
export const LOG_IN_REQUEST = "LOG_IN_REQUEST"
export const LOG_IN_REQUEST_SUCCESS = "LOG_IN_REQUEST_SUCCESS"
export const LOG_IN_REQUEST_FAIL = "LOG_IN_REQUEST_FAIL"
